packages:
  - '.'

publicHoistPattern:
  - '*@nextui-org/*'

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@tsparticles/engine': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@sahan-sac/auth-kit@0.2.0 || 0.3.0'
